### PR TITLE
SM-3155: Fix okio version range for okhttp-2.2.0

### PR DESCRIPTION
**Pull request by googlielmo**

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by oscerd** [comment]
@jbonofre I've some minutes, I'll merge this one.

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close the PR?

I had to add the bundle to the bundles list to release

https://github.com/apache/servicemix-bundles/commit/609eb4b58e2df7a10e6a688c1b0faa7afcb42066

**Comment by jbonofre** [comment]
I will close using an empty commit.

**Pull request closed without merging**
