### PR TITLE
[SMX-5720] Upgrade Spring 6.1.10

### PR DESCRIPTION
**Pull request by mattrpav**

### CODE REVIEW

**Comment by jbonofre** [comment]
The PR is not fully correct as the parent pom.xml has not been updated. I will fix that and prepare the next release cycle.

**Comment by jbonofre** [comment]
Including it as part of my release prep script.

**Comment by mattrpav** [comment]
@jbonofre heads up-- Spring 6.1.11 just released

**Comment by jbonofre** [comment]
@mattrpav see https://issues.apache.org/jira/browse/SM-5720

**Pull request closed without merging**
