### PR TITLE
Sm 5055 azure version updates

### PR DESCRIPTION
**Pull request by jojansen**
added new azure-bundlees with updated versions.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM, but you need to add them the main pom for the release cycle.

**Comment by oscerd** [comment]
Here: 
https://github.com/apache/servicemix-bundles/blob/master/pom.xml

The other bundle in the modules section, have been released already, so you can remove them and add the ones from your PR.

**Comment by jojansen** [comment]
@oscerd: thanks for your response. 
I did the mentioned steps and pushed everything again.

**Comment by jbonofre** [comment]
Do you mind if I create the corresponding jira and amend your git comments with the jira ? It's better for the tracking. Ok ?

**Comment by jojansen** [comment]
sure it's fine for me :-)

**Pull request closed without merging**
