### PR TITLE
Fix OkHttp 4.10.0 bundle import

### PR DESCRIPTION
**Pull request by dalbani**
As `okio-jvm` exports version 3.0.0.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
We'll need to release this again I guess, but in the next release cycle @jbonofre

**Comment by jbonofre** [comment]
Good catch. I did the change locally (by my script) but forgot to `git push` :( My bad. I will include in next release cycle.

**Comment by dalbani** [comment]
I am also curious how the `servicemix.osgi.import.pkg` is determined: by an automated script or by hand?

**Comment by jbonofre** [comment]
@dalbani my script is using bnd to get the import and define the required import (I have some pattern to define optional import, private, etc). However, the version range are defined by hand (when I validate the statements generated by the script).
So, here, it's my fault, I forgot to update it.

**Review by jbonofre — APPROVED** [review]

**Pull request merged**
