### PR TITLE
[SM-2703] Create OSGi bundle for Libthrift 0.9.3

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR is related to:
https://issues.apache.org/jira/browse/SM-2703

Andrea

### CODE REVIEW

**Comment by oscerd** [comment]
Rebased

**Comment by jbonofre** [comment]
The scm element is missing, I'm fixing that.

**Comment by oscerd** [comment]
Sorry for that..
Il 29/ott/2015 07:04, "Jean-Baptiste Onofré" <notifications@github.com> ha
scritto:

**Comment by jbonofre** [comment]
No problem !

**Pull request merged**
