### PR TITLE
upgrade to kafka 0.11.0.1 and set kafka-streams as fragment host of kafka-clients

### PR DESCRIPTION
**Pull request by hlavki**
working karaf feature is:
```xml
    <feature name="rocksdb" version="5.2.1">
        <bundle>wrap:mvn:org.rocksdb/rocksdbjni/5.2.1</bundle>
    </feature>

    <feature name="kafka-clients" version="0.11.0.1">
        <feature version="5.2.1">rocksdb</feature>
        <bundle>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.kafka-clients/0.11.0.1_1</bundle>
        <bundle>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.kafka-streams/0.11.0.1_1</bundle>
    </feature>
```

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by hlavki** [comment]
@jbonofre Does kafka-streams work without fragment-host? Because it didn't work for me. thanks

**Comment by tomdw** [comment]
Can you also fix that the import package should not be on an non-existing org.apache.kafka.client package but on existing org.apache.kafka.clients packages ?

**Comment by jbonofre** [comment]
Yeah. I will take a look and fix for next release cycle.

**Comment by jbonofre** [comment]
I don't think those changes are required. `kafka-streams` can work standalone (no need to use a fragment).
I'm closing this PR. Please, create a Jira if it doesn't work for you (as now the kafka-stream imports are fixed with #108).

**Comment by hlavki** [comment]
@jbonofre, you are right, it works without fragment-host, but it doesn't work without org.rocksdb import.

**Pull request closed without merging**
