### PR TITLE
SM-5705: Create OSGi bundles for Spring 5.3.34

### PR DESCRIPTION
**Pull request by smmribeiro**
With this PR I'm upgrading the existing OSGi bundles for Spring to version 5.3.34 (based it on what was done for the 5.3.33 version).

On the corresponding issue ([SM-5705](https://issues.apache.org/jira/browse/SM-5705)), I've also attached a [patch](https://issues.apache.org/jira/secure/attachment/13068608/SM-5705-Create-OSGi-bundles-for-Spring-5.3.34.patch.txt).

### CODE REVIEW

**Comment by jbonofre** [comment]
@smmribeiro Thanks ! I will take a look because some bundles need fixes/improvements (detected on 5.3.33 bundles).

**Review by jbonofre — APPROVED** [review]

**Comment by smmribeiro** [comment]
@oscerd, @jbonofre
Just to manage expectations, is there an ETA for the new release?

**Comment by jbonofre** [comment]
@smmribeiro the vote should start next week, so, if ok, the release will be available by the end of May.

**Comment by smmribeiro** [comment]
Thank you @jbonofre

**Pull request merged**
