### PR TITLE
org.conscrypt.*;resolution:=optional

### PR DESCRIPTION
**Pull request by eddurov**
Perhaps, conscrypt is optional ?

### CODE REVIEW

**Comment by jbonofre** [comment]
R: @jbonofre

**Comment by oscerd** [comment]
@jbonofre I'm merging this.

**Comment by jbonofre** [comment]
OK. Next time don't forget to ask for update in the main `pom.xml` in order to include the bundle in the next release cycle.

**Comment by oscerd** [comment]
This has been merged and added to next relese cycle, can you close the PR?

**Comment by eddurov** [comment]
done

**Pull request closed without merging**
