### PR TITLE
[SM-5180] Create OSGi bundle for okhttp 4.9.3

### PR DESCRIPTION
**Pull request by CMoH**

### CODE REVIEW

**Comment by CMoH** [comment]
Should I create a Jira issue for this? I noticed many such commits have one, but I am not sure if it should be me that creates it.

**Comment by jbonofre** [comment]
I created https://issues.apache.org/jira/browse/SM-5180. I will merge by hand to update the commit message. Thanks.

**Comment by CMoH** [comment]
> I created https://issues.apache.org/jira/browse/SM-5180. I will merge by hand to update the commit message. Thanks.

I did that and force pushed - hope it helps!

I'll make sure to create the appropriate Jira issue next time. Thanks for clarifying this.

**Review by jbonofre — APPROVED** [review]

**Comment by jbonofre** [comment]
I merged by hand as I did some modification on your changes (I included new bundles pom version and cleanup "old" okhttp bundle).

**Pull request closed without merging**
