### PR TITLE
SM-3712 Create OSGi bundle for Thymeleaf 3.0.7

### PR DESCRIPTION
**Pull request by oliverlietz**

### CODE REVIEW

**Comment by oscerd** [comment]
Is there a specific reason to have bundles from 3.0.0 to 3.0.9? Usually we release the last one available, but if you have a reason for this it's fine for me

**Comment by oliverlietz** [comment]
@oscerd, the reason is to have fully transparent and reproducible package versions (properly calculated by bnd). _Usually_ bundles from SM export packages using the library version.

**Comment by oscerd** [comment]
@jbonofre wdyt here?

**Comment by jbonofre** [comment]
The bundle should provide the version (not bnd). So,  -1 to have all  those bundles, only latest one is enough.

**Pull request closed without merging**
